# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c697ba6d0a889fa8ba95fa799511d6ab7e6b8e9ebc55e17d22a5340b6cc3ecd40e587aa4fcd8eb6efa3fa95f34a3568b0ee69b222d329cf226003e42a2269e32

test:
  secret_key_base: 92ab26879f57cd5bdb6e0fbec7fc01d3092b37eceb42cba65e53e2831b61a014bfeaeb8d0d4cb6b2033a02b8bc24fff2ab059032bd4f4a769ade1030a42d1670

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
